include!(concat!(env!("OUT_DIR"), "/logos.rs")); // include the logos.rs file generated by build.rs

use crate::info::SystemInfo;
mod info;
mod desktop;

fn main() {
    let info = SystemInfo::new();
    info.display();
    if let Some(logo) = get_logo("fedora") {
        println!("{}", logo);
    }
}


